title: RedHouse Studio
email: gijs@redhouse.nl
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

facebook_url: ''
spotify_url: ''
soundcloud_url: ''

google_analytics: 'UA-2812430-1'

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
